const allowedChannels = [

    "Lemmino ",
    "melodysheep ",
    "Ze Frank biology",
    "Primitive Technology ",
    "Casually Explained comedy, kinda",
    "Applied Science science experiments",
    "Sebastian Lague game dev/comp sci",
    "Crime Pays But Botany Doesn't botany",
    "Veritasium general science",
    "Vagrant Holiday ",
    "Exurb1a philosophy",
    "Marc Rebillet music",
    "NileRed chemistry",
    "Deep Look biology",
    "Hsinchuen Lin ceramics",
    "Deep Sky Videos space",
    "Cooking With The Blues cooking",
    "Real Engineering engineering",
    "StuffMadeHere engineering",
    "Ben Eater computer science",
    "styropyro lasers",
    "3Blue1Brown math",
    "Kurzgesagt - In a Nutshell ",
    "EngineerGuy engineering",
    "Periodic Videos chemistry",
    "Journey to the Microcosmos microbiology, microscopy",
    "Channel 5 with Andrew Callaghan ",
    "Dictionary of Obscure Sorrows ",
    "SethEverman ",
    "Indigo Traveller travel",
    "Armando Hasudungan ",
    "Wendy Riggs ",
    "Medicosis Perfectionalis ",
    "Institute of Human Anatomy ",
    "Chubbyemu ",
    "Ninja Nerd ",
    "Alice Roberts embryology",
    "Sam Webster ",
    "Journey to the Microcosmos microbiology, microscopy",
    "Deep Look ",
    "Crime Pays But Botany Doesn't botany",
    "Ze Frank ",
    "Animalogic ",
    "Fraser Valley Rose Farm botany",
    "Natural World Facts ",
    "Dr. Plants ",
    "Basin79 spiders",
    "Ben G Thomas ",
    "AntsCanada ants",
    "Andrew Millison permaculture",
    "Anthill Art ",
    "TierZoo ",
    "Made in the Wild zoology",
    "Stated Clearly ",
    "MBARI marine biology",
    "Anthony Pain ",
    "Nature on PBS ",
    "BBC Earth ",
    "Microbehunter microscopy, microbiology",
    "Quaoar Power entomology",
    "Animal Fact Files ",
    "Cornell Lab of Ornithology ",
    "Planet Fungi mycology",
    "Atlas Pro ",
    "Amoeba Sisters ",
    "EVNautilus marine biology",
    "InsecthausTV insects",
    "Plants Insider ",
    "Neural Academy biology songs",
    "Biologybyme ",
    "This Glorious Clockwork ",
    "Simon Clark climate",
    "OceanVizion 4k sea life",
    "ChrisFix automotive",
    "HVAC-R Videos ",
    "Speedkar99 automotive",
    "AC Service Tech LLC HVAC",
    "HVAC School ",
    "Word of Advice TV HVAC, plumbing",
    "MikeHoltNEC electrical",
    "Project Farm tools, DIY",
    "Electrician U ",
    "Essential Craftsman construction",
    "RR Buildings construction",
    "Perkins Builder Brothers construction",
    "Insider Carpentry ",
    "Fix This Build That ",
    "NileRed ",
    "Periodic Videos ",
    "Tyler DeWitt ",
    "NurdRage ",
    "NileRed Shorts ",
    "NileBlue ",
    "Extractions&Ire ",
    "Explosions&Fire ",
    "ChemicalForce ",
    "Chemdelic ",
    "Rhodanide ",
    "Tom's Lab ",
    "ReactiveChem ",
    "David Sherrill computational chemistry",
    "TMP Chem ",
    "Chemistry in a Nutshell lectures",
    "The Organic Chemistry Tutor lectures",
    "Reid Gower feynman, sagan",
    "Hsinchuen Lin ceramics",
    "Ingleton Pottery ",
    "Yukikawae sand drawing",
    "Macro Room ",
    "Ben Eater ",
    "Sebastian Lague ",
    "Two Minute Papers ",
    "george hotz archive ",
    "Computerphile ",
    "LiveOverflow ",
    "jdh ",
    "Kevin Fang internet disasters",
    "Reducible ",
    "PwnFunction ",
    "CS Dojo ",
    "sentdex ",
    "Fireship ",
    "javidx9 ",
    "Welch Labs ",
    "CodeParade ",
    "DevTips ",
    "ExplainingComputers ",
    "Neso Academy ",
    "The Coding Train ",
    "Nemean ",
    "Brackeys ",
    "Code Bullet ",
    "DeepMind applied computer science",
    "Creel ",
    "Techquickie ",
    "Linus Tech Tips ",
    "Scrimba learn how to code interactively [website]",
    "Mike Dane every language",
    "freeCodeCamp every language",
    "mCoding python",
    "Programming with Mosh java, python",
    "Bro Code ",
    "Corey Schafer mainly python, pandas, django",
    "TheCodex java, SQL, python",
    "John Hammond ",
    "Stephen Grider ",
    "JavaScript Mastery ",
    "Kevin Powell HTML & CSS",
    "The Net Ninja ",
    "Mr. P Solver python",
    "Coding Addict ",
    "IAmTimCorey C#",
    "Alex Lee java",
    "Dev Ed react, JS, node JS, web design",
    "Ari Pxl figma, HTML, CSS",
    "DesignCode UI/UX, figma, swift",
    "Web Dev Simplified CSS, JS, React, Node",
    "Vlog Creations ",
    "Casually Explained ",
    "Incognito Mode ",
    "Alex Ernst apple cider vinegar",
    "Lessons in Meme Culture ",
    "SomethingAboutChickens ",
    "Kill Tony stand up",
    "Just For Laughs Gags ",
    "schmoyoho ",
    "Berd ",
    "Internet Comment Etiquette ",
    "surreal entertainment ",
    "twomad ",
    "Jelle's Marble Runs ",
    "Tico & the Man Frank Maglio ",
    "Cart Narcs ",
    "Cooking Con Claudia ",
    "ArnieTex ",
    "Cooking With The Blues ",
    "SAM THE COOKING GUY ",
    "J. Kenji L\u00f3pez-Alt ",
    "Chaplin's Classics ",
    "Chinese Cooking Demystified ",
    "Yeung Man Cooking ",
    "Tasting History with Max Miller ",
    "Joshua Weissman ",
    "Babish Culinary Universe ",
    "Adam Ragusea ",
    "MinuteFood ",
    "Peter Santenello ",
    "Soft White Underbelly ",
    "FRONTLINE PBS | Official ",
    "Channel 5 with Andrew Callaghan ",
    "All Gas No Brakes ",
    "Kimgary ",
    "DW Documentary ",
    "VICE ",
    "Nick Zentner geology",
    "Stefan Milo anthropology/archeology",
    "PBS Eons ",
    "History of the Earth ",
    "Kate Tectonics geology",
    "The Budget Museum ",
    "Climate Town climate",
    "Animal Origins ",
    "Moth Light Media ",
    "NORTH 02 ",
    "PBS Terra earth science",
    "Your Dinosaurs Are Wrong ",
    "Past Eons Productions ",
    "GeologyHub ",
    "GeologyUpSkill geology",
    "Mr Carlson's Lab ",
    "Simply Electronics ",
    "Technology Connections ",
    "SeanHodgins ",
    "styropyro lasers",
    "How To Mechatronics ",
    "DiodeGoneWild ",
    "bigclivedotcom ",
    "GreatScott! ",
    "Afrotechmods ",
    "Zilipoper ",
    "Vidduley ",
    "JerryRigEverything ",
    "ElectroBOOM ",
    "The Signal Path ",
    "Esperantanaso ",
    "Techmoan ",
    "EEVblog ",
    "EdisonTechCenter ",
    "Moritz Klein ",
    "w2aew ",
    "CuriousMarc ",
    "Tesla500 ",
    "Alan Yates ",
    "Mikeselectricstuff ",
    "Jeri Ellsworth ",
    "Marques Brownlee new tech",
    "FesZ Electronics ",
    "Ali Hajimiri ",
    "Electronoobs ",
    "Marco Reps ",
    "NorthridgeFix electronic repair",
    "EngineerGuy ",
    "Real Engineering ",
    "Practical Engineering civil",
    "The Efficient Engineer ",
    "Ziroth ",
    "The Engineering Mindset ",
    "Engineering Explained ",
    "Kyle.Engineers ",
    "AgentJayZ ",
    "Undecided with Matt Ferrell ",
    "The B1M civil",
    "Found And Explained aerospace",
    "Lesics ",
    "Dejmian XYZ Simulations ",
    "Art of rendering mechanical renders",
    "WolfShaft mechanical renders",
    "Jeff Hanson lectures",
    "Gregory Michaelson statics, structural analysis",
    "Boston Dynamics ",
    "Frost ",
    "Ahoy ",
    "Hollow ",
    "theRadBrad ",
    "MKIceAndFire ",
    "videogamedunkey ",
    "ThrillSeeker ",
    "Kurzgesagt - In a Nutshell ",
    "Lemmino ",
    "melodysheep ",
    "Mike Boyd ",
    "Wendover Productions ",
    "Joe Scott ",
    "D!NG ",
    "Half as Interesting ",
    "Tom Scott ",
    "Primer ",
    "New Mind ",
    "Vsauce ",
    "Vsauce2 ",
    "TED-Ed ",
    "Atomic Frontier ",
    "Facts in Motion ",
    "Jared Owen ",
    "Koranos ",
    "Art of the Problem ",
    "RealLifeLore ",
    "Vox ",
    "CGP Grey ",
    "Geographics ",
    "Biographics ",
    "Veritasium ",
    "Domain of Science ",
    "Sabine Hossenfelder ",
    "The Action Lab ",
    "Steve Mould ",
    "Be Smart ",
    "Science Channel ",
    "NightHawkInLight ",
    "Branch Education ",
    "Science Marshall ",
    "Sciencephile the AI ",
    "Sci Show ",
    "Minute Earth ",
    "Real Science ",
    "Alpha Phoenix ",
    "Arxiv Insights ",
    "Nottinghamscience ",
    "BackstageScience ",
    "Verge Science ",
    "The Royal Institution ",
    "World Science Festival ",
    "Up and Atom ",
    "SmarterEveryDay ",
    "Kyle Hill ",
    "StarTalk ",
    "Sam O'Nella Academy ",
    "History Matters ",
    "toldinstone ",
    "Dan Carlin ",
    "TimeGhost History ",
    "Kings and Generals ",
    "The History Guy ",
    "Jay Foreman ",
    "The Operations Room ",
    "Historia Civilis ",
    "ConeOfArc ",
    "Paper Skies ",
    "Dan Davis History ",
    "History Buffs ",
    "Military History Visualized ",
    "HistoryMarche ",
    "OverSimplified ",
    "Fire of Learning ",
    "The Great War ",
    "Drachinifel ",
    "Lindybeige ",
    "InRangeTV ",
    "Invicta ",
    "Forgotten Weapons ",
    "Fall of Civilizations ",
    "Tasting History with Max Miller ",
    "Weird History ",
    "Real Crusades History ",
    "The Chieftain ",
    "Knowledgia ",
    "Extra Credits ",
    "Rex's Hangar ",
    "WW1 [Playlist] ",
    "WW2 [Playlist] ",
    "PLANTERINA houseplants",
    "Nick Pileggi houseplants",
    "SerpaDesign terrariums",
    "Asu terrariums",
    "Jartopia terrariums",
    "MD Fish Tanks houseplants",
    "SethEverman ",
    "Dillon The Hacker ",
    "Crash Course ",
    "Khan Academy ",
    "AK Lectures ",
    "Michel van Biezen ",
    "MIT OpenCourseWare ",
    "Bozeman Science physics, biology",
    "YaleCourses ",
    "Harvard Physics ",
    "Professor Dave Explains chemistry, anatomy",
    "3Blue1Brown ",
    "Numberphile ",
    "PBS Infinite Series ",
    "Eddie Woo ",
    "Vihart ",
    "Stand-up Maths ",
    "Mathologer ",
    "patrickJMT ",
    "Tipping Point Math ",
    "Think Twice ",
    "blackpenredpen ",
    "MindYourDecisions ",
    "Richard E. BORCHERDS advanced math",
    "Dr. Trefor Bazett ",
    "Professor Leonard lectures",
    "Tibees ",
    "Michael Penn ",
    "zhuli ",
    "Mateusz M ",
    "Better Ideas ",
    "George Collier ",
    "12tone music theory",
    "Tony Ann piano",
    "Frank Watkinson guitar",
    "Kyle Landry piano",
    "Paul Davids guitar",
    "Alex Ball synths",
    "Ichika Nito guitar",
    "ibi piano",
    "Mariana Froes singing covers",
    "CharlesBerthoud bass",
    "Daniel Thrasher ",
    "The Dooo electric guitar",
    "Harry Mack freestyle rap",
    "Fkj ",
    "Markus Veltri piano",
    "Marc Rebillet improv music",
    "DOMi & JD Beck ",
    "Lara6683 piano",
    "Majestic Casual ",
    "MrSuicideSheep ",
    "Steezyasfuck ",
    "Adam Neely ",
    "David Bruce Composer ",
    "Sideways music analysis",
    "8-bit Music Theory ",
    "Captain Pikant ",
    "Electr\u00f3nicos Fant\u00e1sticos! ",
    "Dolomuse ",
    "Listening In ",
    "Tantacrul ",
    "Charles Cornell ",
    "David Bennett Piano ",
    "Primitive Technology ",
    "Self Sufficient Me gardening",
    "Kraig Adams hiking",
    "Alaska to Argentina on Honda 90's travel",
    "Beau Miles ",
    "Bertram - Craft and Wilderness ",
    "Patagonia ",
    "AlfieAesthetics ",
    "Learn Your Land ",
    "Yellow Elanor ",
    "Paul Stamets mycology",
    "MCQBushcraft ",
    "Nagualero ",
    "Primitive Skills ",
    "Bound For Nowhere ",
    "Foresty Forest ",
    "Jungle Survival - fake  but cool",
    "Primitive Survival Tool - fake  but cool",
    "Exurb1a ",
    "Dictionary of Obscure Sorrows ",
    "Sisyphus 55 ",
    "Pursuit of Wonder ",
    "Minutephysics ",
    "PBS Space Time ",
    "Fermilab - quantum ",
    "The Science Asylum ",
    "Physics with Elliot ",
    "Physics Girl ",
    "Physics Videos by Eugene ",
    "ScienceClic English ",
    "braintruffle ",
    "Xenosum ",
    "DrPhysicsA ",
    "For the Allure of Physics ",
    "ViaScience - quantum mechanics  thermodynamics",
    "XylyXylyX - general relativity ",
    "Sixty Symbols ",
    "PhysicsHigh ",
    "Parth G ",
    "Looking Glass Universe ",
    "Arvin Ash ",
    "Physics Explained ",
    "The Biggest Ideas in the Universe - playlist ",
    "Eigenchris - relativity  tensors",
    "Flipping Physics ",
    "Physics Explained ",
    "Professor M does Science ",
    "Applied Science ",
    "Thought Emporium ",
    "StuffMadeHere ",
    "Jeremy Fielding ",
    "Tech Ingredients ",
    "Sam Zeloof ",
    "Mark Rober ",
    "Cody's Lab ",
    "Michael Reeves ",
    "colinfurze ",
    "TheBackyardScientist ",
    "The Post Apocalyptic Inventor ",
    "Tom Stanton ",
    "PeterSripol ",
    "rctestflight ",
    "Huygens Optics ",
    "Teslista555 high voltage",
    "Breaking Taps ",
    "Sam O'Nella Academy ",
    "History Matters ",
    "toldinstone ",
    "Dan Carlin ",
    "TimeGhost History ",
    "Kings and Generals ",
    "The History Guy ",
    "Jay Foreman ",
    "The Operations Room ",
    "Historia Civilis ",
    "ConeOfArc ",
    "Paper Skies ",
    "Dan Davis History ",
    "History Buffs ",
    "Military History Visualized ",
    "HistoryMarche ",
    "OverSimplified ",
    "Fire of Learning ",
    "The Great War ",
    "Drachinifel ",
    "Lindybeige ",
    "InRangeTV ",
    "Invicta ",
    "Forgotten Weapons ",
    "Fall of Civilizations ",
    "Tasting History with Max Miller ",
    "Weird History ",
    "Real Crusades History ",
    "The Chieftain ",
    "Knowledgia ",
    "Extra Credits ",
    "Rex's Hangar ",
    "WW1 [Playlist] ",
    "WW2 [Playlist] ",
    "PLANTERINA houseplants",
    "Nick Pileggi houseplants",
    "SerpaDesign terrariums",
    "Asu terrariums",
    "Jartopia terrariums",
    "MD Fish Tanks houseplants",
    "SethEverman ",
    "Dillon The Hacker ",
    "Crash Course ",
    "Khan Academy ",
    "AK Lectures ",
    "Michel van Biezen ",
    "MIT OpenCourseWare ",
    "Bozeman Science physics, biology",
    "YaleCourses ",
    "Harvard Physics ",
    "Professor Dave Explains chemistry, anatomy",
    "3Blue1Brown ",
    "Numberphile ",
    "PBS Infinite Series ",
    "Eddie Woo ",
    "Vihart ",
    "Stand-up Maths ",
    "Mathologer ",
    "patrickJMT ",
    "Tipping Point Math ",
    "Think Twice ",
    "blackpenredpen ",
    "MindYourDecisions ",
    "Richard E. BORCHERDS advanced math",
    "Dr. Trefor Bazett ",
    "Professor Leonard lectures",
    "Tibees ",
    "Michael Penn ",
    "zhuli ",
    "Mateusz M ",
    "Better Ideas ",
    "George Collier ",
    "12tone music theory",
    "Tony Ann piano",
    "Frank Watkinson guitar",
    "Kyle Landry piano",
    "Paul Davids guitar",
    "Alex Ball synths",
    "Ichika Nito guitar",
    "ibi piano",
    "Mariana Froes singing covers",
    "CharlesBerthoud bass",
    "Daniel Thrasher ",
    "The Dooo electric guitar",
    "Harry Mack freestyle rap",
    "Fkj ",
    "Markus Veltri piano",
    "Marc Rebillet improv music",
    "DOMi & JD Beck ",
    "Lara6683 piano",
    "Majestic Casual ",
    "MrSuicideSheep ",
    "Steezyasfuck ",
    "Adam Neely ",
    "David Bruce Composer ",
    "Sideways music analysis",
    "8-bit Music Theory ",
    "Captain Pikant ",
    "Electr\u00f3nicos Fant\u00e1sticos! ",
    "Dolomuse ",
    "Listening In ",
    "Tantacrul ",
    "Charles Cornell ",
    "David Bennett Piano ",
    "Primitive Technology ",
    "Self Sufficient Me gardening",
    "Kraig Adams hiking",
    "Alaska to Argentina on Honda 90's travel",
    "Beau Miles ",
    "Bertram - Craft and Wilderness ",
    "Patagonia ",
    "AlfieAesthetics ",
    "Learn Your Land ",
    "Yellow Elanor ",
    "Paul Stamets mycology",
    "MCQBushcraft ",
    "Nagualero ",
    "Primitive Skills ",
    "Bound For Nowhere ",
    "Foresty Forest ",
    "Jungle Survival - fake  but cool",
    "Primitive Survival Tool - fake  but cool",
    "Exurb1a ",
    "Dictionary of Obscure Sorrows ",
    "Sisyphus 55 ",
    "Pursuit of Wonder ",
    "Minutephysics ",
    "PBS Space Time ",
    "Fermilab - quantum ",
    "The Science Asylum ",
    "Physics with Elliot ",
    "Physics Girl ",
    "Physics Videos by Eugene ",
    "ScienceClic English ",
    "braintruffle ",
    "Xenosum ",
    "DrPhysicsA ",
    "For the Allure of Physics ",
    "ViaScience - quantum mechanics  thermodynamics",
    "XylyXylyX - general relativity ",
    "Sixty Symbols ",
    "PhysicsHigh ",
    "Parth G ",
    "Looking Glass Universe ",
    "Arvin Ash ",
    "Physics Explained ",
    "The Biggest Ideas in the Universe - playlist ",
    "Eigenchris - relativity  tensors",
    "Flipping Physics ",
    "Physics Explained ",
    "Professor M does Science ",
    "Applied Science ",
    "Thought Emporium ",
    "StuffMadeHere ",
    "Jeremy Fielding ",
    "Tech Ingredients ",
    "Sam Zeloof ",
    "Mark Rober ",
    "Cody's Lab ",
    "Michael Reeves ",
    "colinfurze ",
    "TheBackyardScientist ",
    "The Post Apocalyptic Inventor ",
    "Tom Stanton ",
    "PeterSripol ",
    "rctestflight ",
    "Huygens Optics ",
    "Teslista555 high voltage",
    "Breaking Taps ",
    "Sam O'Nella Academy ",
    "History Matters ",
    "toldinstone ",
    "Dan Carlin ",
    "TimeGhost History ",
    "Kings and Generals ",
    "The History Guy ",
    "Jay Foreman ",
    "The Operations Room ",
    "Historia Civilis ",
    "ConeOfArc ",
    "Paper Skies ",
    "Dan Davis History ",
    "History Buffs ",
    "Military History Visualized ",
    "HistoryMarche ",
    "OverSimplified ",
    "Fire of Learning ",
    "The Great War ",
    "Drachinifel ",
    "Lindybeige ",
    "InRangeTV ",
    "Invicta ",
    "Forgotten Weapons ",
    "Fall of Civilizations ",
    "Tasting History with Max Miller ",
    "Weird History ",
    "Real Crusades History ",
    "The Chieftain ",
    "Knowledgia ",
    "Extra Credits ",
    "Rex's Hangar ",
    "WW1 [Playlist] ",
    "WW2 [Playlist] ",
    "PLANTERINA houseplants",
    "Nick Pileggi houseplants",
    "SerpaDesign terrariums",
    "Asu terrariums",
    "Jartopia terrariums",
    "MD Fish Tanks houseplants",
    "SethEverman ",
    "Dillon The Hacker ",
    "Crash Course ",
    "Khan Academy ",
    "AK Lectures ",
    "Michel van Biezen ",
    "MIT OpenCourseWare ",
    "Bozeman Science physics, biology",
    "YaleCourses ",
    "Harvard Physics ",
    "Professor Dave Explains chemistry, anatomy",
    "3Blue1Brown ",
    "Numberphile ",
    "PBS Infinite Series ",
    "Eddie Woo ",
    "Vihart ",
    "Stand-up Maths ",
    "Mathologer ",
    "patrickJMT ",
    "Tipping Point Math ",
    "Think Twice ",
    "blackpenredpen ",
    "MindYourDecisions ",
    "Richard E. BORCHERDS advanced math",
    "Dr. Trefor Bazett ",
    "Professor Leonard lectures",
    "Tibees ",
    "Michael Penn ",
    "zhuli ",
    "Mateusz M ",
    "Better Ideas ",
    "George Collier ",
    "12tone music theory",
    "Tony Ann piano",
    "Frank Watkinson guitar",
    "Kyle Landry piano",
    "Paul Davids guitar",
    "Alex Ball synths",
    "Ichika Nito guitar",
    "ibi piano",
    "Mariana Froes singing covers",
    "CharlesBerthoud bass",
    "Daniel Thrasher ",
    "The Dooo electric guitar",
    "Harry Mack freestyle rap",
    "Fkj ",
    "Markus Veltri piano",
    "Marc Rebillet improv music",
    "DOMi & JD Beck ",
    "Lara6683 piano",
    "Majestic Casual ",
    "MrSuicideSheep ",
    "Steezyasfuck ",
    "Adam Neely ",
    "David Bruce Composer ",
    "Sideways music analysis",
    "8-bit Music Theory ",
    "Captain Pikant ",
    "Electr\u00f3nicos Fant\u00e1sticos! ",
    "Dolomuse ",
    "Listening In ",
    "Tantacrul ",
    "Charles Cornell ",
    "David Bennett Piano ",
    "Primitive Technology ",
    "Self Sufficient Me gardening",
    "Kraig Adams hiking",
    "Alaska to Argentina on Honda 90's travel",
    "Beau Miles ",
    "Bertram - Craft and Wilderness ",
    "Patagonia ",
    "AlfieAesthetics ",
    "Learn Your Land ",
    "Yellow Elanor ",
    "Paul Stamets mycology",
    "MCQBushcraft ",
    "Nagualero ",
    "Primitive Skills ",
    "Bound For Nowhere ",
    "Foresty Forest ",
    "Jungle Survival - fake  but cool",
    "Primitive Survival Tool - fake  but cool",
    "Exurb1a ",
    "Dictionary of Obscure Sorrows ",
    "Sisyphus 55 ",
    "Pursuit of Wonder ",
    "Minutephysics ",
    "PBS Space Time ",
    "Fermilab - quantum ",
    "The Science Asylum ",
    "Physics with Elliot ",
    "Physics Girl ",
    "Physics Videos by Eugene ",
    "ScienceClic English ",
    "braintruffle ",
    "Xenosum ",
    "DrPhysicsA ",
    "For the Allure of Physics ",
    "ViaScience - quantum mechanics  thermodynamics",
    "XylyXylyX - general relativity ",
    "Sixty Symbols ",
    "PhysicsHigh ",
    "Parth G ",
    "Looking Glass Universe ",
    "Arvin Ash ",
    "Physics Explained ",
    "The Biggest Ideas in the Universe - playlist ",
    "Eigenchris - relativity  tensors",
    "Flipping Physics ",
    "Physics Explained ",
    "Professor M does Science ",
    "Applied Science ",
    "Thought Emporium ",
    "StuffMadeHere ",
    "Jeremy Fielding ",
    "Tech Ingredients ",
    "Sam Zeloof ",
    "Mark Rober ",
    "Cody's Lab ",
    "Michael Reeves ",
    "colinfurze ",
    "TheBackyardScientist ",
    "The Post Apocalyptic Inventor ",
    "Tom Stanton ",
    "PeterSripol ",
    "rctestflight ",
    "Huygens Optics ",
    "Teslista555 high voltage",
    "Breaking Taps ",
    "Lex Fridman Podcast long form discussions with the world's greatest minds",
    "Radiolab investigative journalism, storytelling",
    "Invention history and impact of different inventions",
    "This Podcast Will Kill You diseases, epidemiology, public health",
    "Hardcore History deep dives into historical events",
    "Materialism material science",
    "Ologies interviewing people with different science jobs",
    "Big Biology biology topics",
    "Astronomy Cast astronomy in an accessible manner",
    "Stuff to Blow Your Mind random cool stuff",
    "Origin Stories evolution and anthropology",
    "Life's Little Mysteries general science",
    "The Anthropocene Reviewed reviewing aspects of earth on a 5 star scale",
    "50 Things That Made the Modern Economy history and significance of inventions",
    "Speaking of Bitcoin cryptocurrency discussion",
    "30 Animals That Made Us Smarter animals and human innovation",
    "Huberman Lab Podcast neuroscience and human performance",
    "After On science and technology, futurism",
    "Unscrypted Podcast cryptocurrency fundamentals",
    "TWIV (This Week in Virology) current state of virology",
    "Daniel and Jorge Explain the Universe cosmology and particle physics",
    "Planetary Radio space exploration and astronomy",
    "Planetary Radio: Space Policy Edition space policy",
    "Safety Third popular science YouTubers",
    "The Biologic Podcast biology",
    "Talk Nerdy with Cara conversations with scientists",
    "The Skeptics Guide to the Universe scientific topics from a skeptical perspective",
    "Geology on the Rocks geology",
    "99% Invisible design, sound design and storytelling"
    ];

console.log("Whitelist loaded with", allowedChannels.length, "channels.");